### PR TITLE
fix: Remove optional <span> elements for Gloss and Reference during Lift export

### LINKED ISSUE #72: bug: Remove optional spans in <text> elements during SA Lift export
Report from Jennifer

> Okay, I just noticed this morning that when using the LIFT feature, the English gloss has a return and 10 spaces in front of the English gloss in FLEx.

> The first entry "sky", I deleted the white space from. The other entries show the white space, which was more evident with the students' data because there was text wrapping involved.  It basically looks like a hanging indent at that point.
00ctrdVPkMdtBEVi

--------

Looking at the Lift 13 file that SA exports:
```xml
    <sense id="45ccc726-4903-4b78-b47c-5fc06557f1d5" order="0">
      <gloss lang="en">
        <text>
          <span>say-3sing.Sequential</span>
        </text>
      </gloss>
      <gloss lang="es">
        <text>
          <span>tacos</span>
        </text>
      </gloss>
    </sense>
```

Currently, SA lift export is using optional `<span>` elements for each `<text>` element, and it appears FLEx is rendering those extra lines/spaces.

Contrasting with WeSay Lift file or when I remove the whitespace in FLEx and do a Lift export from Flex, the results are `<text>` elements without `<span>`s

```xml
<gloss lang="en"><text>say-3sing.Remote</text></gloss>
```

### Workaround
In FLEx, use the following for **Bulk Edit Operation** setup to remove the extra whitespace
("Use regular expressions" checked)

| Replace        |                     |
|---------------|--------------|
|Find what:      | ^\s+(.+)\s+ |
| Replace with: | $1               |

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #72 

This removes the optional `<span>` elements in some `<text>`  elements during Lift export.

The change is limited to gloss and reference fields.  I was not able to remove the `<span>` elements in the label, because FLEx would throw exceptions in the Lift validation.

Jennifer tested and noted:
> As you said, looks like the gloss and reference number white space issues are taken care of, but the label still has white space.  Texts and words seem to function fine now.

She's fine with the extra whitespace in the labels.

### CODE REVIEW

File: Src/LiftUtils/Lift13.h [hunk 1]
```diff
@@ -708,6 +719,11 @@ class gloss : public form {
         trait(L"trait") {
     };
 
+    gloss(LPCTSTR _name, LPCTSTR _lang, LPCTSTR _data) : //text _text) : //LPCTSTR _lang, LPCTSTR _data) :
```
Comment (darcywong00) [inline Src/LiftUtils/Lift13.h:722]: I will clean up this commented old code

**Review by kgorham — APPROVED** [review]
