### PR TITLE
fix: Use temp wav file on "Save As" for mp3 files

### LINKED ISSUE #49: bug: Error on "Save As" with mp3 file
There's not yet enough information here to reproduce, but I'm creating an issue here to track this post.

https://community.software.sil.org/t/why-cannot-i-save-my-sa-audio/5380

@terrygibbs can you try and reproduce the error and offer some more explanation in this issue and on the community site?  Thanks.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #49 

Currently, when a user opens an mp3 file and attempts "Save As", the app is expecting a waveform file to already exist.

This PR updates the "Save As" File menu option to use the temporary waveform when an mp3 file is involved.

TODO
- [x] more testing

### CODE REVIEW

**Comment by darcywong00** [comment]
From @kgorham 

> @darcywong00 I tried your download link. Seemed to run fine. (uninstalled old SA and reinstalled new). As an improvement, I would suggest stealing some of the code that is in place already, and use the first part of the original filename for the new filename instead of using the .tmp filename. @terrygibbs can second that opinion or not...
> 
> image

File: Src/SA/SA_View.cpp [hunk 1]
```diff
@@ -11639,7 +11639,18 @@ void CSaView::OnFileSaveAs() {
...
-		path = FileUtils::ReplaceExtension((LPCTSTR)path, L".wav").c_str();
+
+		if (FileUtils::EndsWith((LPCTSTR)path, L".mp3")) {
+			// If path is mp3 file, use the temporary converted wavefile already in use:
+			CString tempConvertedWav = doc.GetConvertedWaveFilename().c_str();
+			if (!doc.CheckWaveFormatForOpen(tempConvertedWav)) {
+				app.ErrorMessage(IDS_ERROR_CANT_READ_WAVE_FILE, (LPCTSTR)tempConvertedWav);
+				return;
+			}
+			path = doc.GetConvertedWaveFilename().c_str();
```
Comment (megahirt) [inline Src/SA/SA_View.cpp:11650]: I agree with @kgorham 's [suggestion ](https://github.com/sillsdev/SpeechAnalyzer/pull/54#issuecomment-969583285)to make the saved filePath be the original MP3 filepath except changed to wav file extension.

I don't know this code, but if we are dealing with a fully qualified filePath then I might recommend adding some helper functions e.g.

`FileUtils::ReplaceFilename(fullPath, newFilename)` - replaces the filename in `fullPath`
`FileUtils::GetFilename(fullPath)` - returns just the filename portion of the path including extension

**Review by megahirt — CHANGES_REQUESTED** [review]
Nice work @darcywong00 .  I agree with @kgorham 's suggested change and request those changes - see comment inline.

File: Src/SA/SA_View.cpp (hunk 1 above)
Comment (darcywong00) [reply Src/SA/SA_View.cpp:11650]: I can try to do this.  I'd have to copy the temporary working wav file into the same temp folder with the original filename, since the missing wav file caused the original crash.

**Review by megahirt — APPROVED** [review]
Thanks @darcywong00
